### PR TITLE
Use shell script to install client JS libs

### PR DESCRIPTION
**Pull request by njoyard**
This PR switches from using Bower to a homemade shell script to install client libraries (bootstrap, font-awesome and flag-icon-css) and their dependencies (jquery), thus removing the need for nodejs altogether.

Note that this is not really optimal because we now need to tell the script to install dependencies manually, but it seems a good compromise given the expected frequency we will update those dependencies.

Also, it is quite easy to add a library that's hosted on github or switch versions (see the code in `bin/install_client_deps.sh`).

I also added the `static` directory to the ignorelist for pep8/flake8. Warnings were generated because of non compliant python scripts in bootstrap test suite, but we don't use those.

### CODE REVIEW

**Comment by jpic** [comment]
Lol, j'aime bien !

**Comment by njoyard** [comment]
:)

**Comment by jpic** [comment]
N1 bro, got all this to work on openshift, however we don't see the nice fonts anymore, nor locally nor in openshift, could you look into that please ?

Thanks !!

**Comment by jpic** [comment]
BTW, you should try to setup an instance on openshift, you'll like it i'm sure, it's so nicely hackable ^^

**Comment by Psycojoker** [comment]
Shouldn't it be a good idea to add some code at the launch of either runserver of even in the settings.py that check if the javascript libs are here and if not download them?

That would simplify the README, automate things and avoid "I've just lost 30min on a stupid mistake" bugs.

**Comment by njoyard** [comment]
@jpic oh, I missed that.
@Psycojoker that's my super-secret goal : have a 1-command install and run sequence.

I'll have a look at that tonight, while you guys drink like morons :)

**Comment by jpic** [comment]
We all agree on that, it's really cool to have you in the team @njoyard !!

**Pull request merged**
