### PR TITLE
Fix font issue

### PR DESCRIPTION
**Pull request by njoyard**
Fixes the issue mentioned by @jpic in #39.

### CODE REVIEW

**Comment by jpic** [comment]
Thanks, could you also paste the error in the git commit description next time you fix a bug ? that's pretty cool to have imho, what do you think ?

**Comment by jpic** [comment]
Regression tests are also cool, ie. 847c413

**Comment by njoyard** [comment]
@jpic you mean the error message returned from lesscpy? Indeed, that would make searching the repo for error messages easier. Will do :)
Regression tests are a good idea. I'll try to move that to manage.py soon, along with testing for 3rd party libraries.

**Comment by jpic** [comment]
Move what ?

**Comment by njoyard** [comment]
The test for lesscpy errors. The idea would be to have everything that can go wrong be tested in manage.py on the first run *and* on travis.

**Comment by jpic** [comment]
oh, right, well if travis tests it then that would prevent any commit that break it from being merged so wouldn't that be curative enough for now ?

**Comment by jpic** [comment]
the website deploys a lottttt faster thanks to your patches !!

**Comment by njoyard** [comment]
yeah bower install is slow as molasses

**Pull request merged**
